### ISSUE TITLE
Uploading the same document multiple times should't be possible

### ISSUE THREAD

**Issue by JuAlMan** [dc4eu/vc#76]
Using image docker.sunet.se/dc4eu/apigw:apiv28

In the current implementation it is possible to upload the same document (identified by authentic_source, document_type and document_id) multiple times without having any effect. When changing document_data or some other attributes it does not seem to have any effect at all, when querying the document you still get the data from the first upload call.

We propose that uploading a document with the same set of authentic_source, document_type and document_id should result in a duplicate key error as these attributes uniquely identify a document in the database.

**Comment by masv3971** [comment]
Should be solved with https://github.com/dc4eu/vc/commit/fbb5f520c817228b1344115139135beec5d40e45.

use docker tag `apiv28`

**Comment by JuAlMan** [comment]
Uploading the same combination of document_id, document_type and authentic_source results in the following error: "document_already_exists". Thus this works now as intended.
But if i just change the document_type, i still get the same error.
For example i tried:
```
"authentic_source": "DE:DRV70001",
"document_id": "123",
"document_type": "PDA1"
```
And then:
```
"authentic_source": "DE:DRV70001",
"document_id": "123",
"document_type": "EHIC"
```
